name: py build project

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  pybuildjob1:
    runs-on: ubuntu-latest
    steps:
      - name: pybuildcheckout
        uses: actions/checkout@v4
      - name: pybuildSetupPython
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Installing required libraries
        run: pip install -r requirements.txt

