name: test
 
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  pybuildjob1:
    runs-on: self-hosted
    steps:
      - name: login as root user in ubunt1u
        run:  echo "hello world"

